USE [Concordance]
GO

/****** Object:  Table [AChristmasCarol].[UniqueWords]    Script Date: 9/1/2017 12:26:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AChristmasCarol].[UniqueWords](
	[Word] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_UniqueWords] PRIMARY KEY CLUSTERED 
(
	[Word] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

